### ISSUE TITLE
Automated docker imagess using github workflows

### ISSUE THREAD

**Issue by starsoccer** [dandanthedev/littletinystorage#18]
Any thoughts on adding automated docker images to be built using github workflows so users dont need to clone and build the image themselves?

**Comment by dandanthedev** [comment]
Ack'd, I'll work on this!

**Comment by dandanthedev** [comment]
It should be working now (https://github.com/dandanthedev/littletinystorage/pkgs/container/littletinystorage)

I'll be closing the issue, please lmk if there's anything wrong with it!

**Comment by starsoccer** [comment]
No seems like something is wrong with the docker image,
```
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '/app/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.16.0
```

**Comment by dandanthedev** [comment]
> No seems like something is wrong with the docker image,
> 
> ```
> node:internal/modules/cjs/loader:1148
>   throw err;
>   ^
> 
> Error: Cannot find module '/app/index.js'
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
>     at Module._load (node:internal/modules/cjs/loader:986:27)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
>     at node:internal/main/run_main_module:28:49 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: []
> }
> 
> Node.js v20.16.0
> ```

Hmm, thats weird. I'll look into this

**Comment by starsoccer** [comment]
Also it would be useful if the readme documented all the env variables to set. Right now I am just trying to get it to run, then going to attempt to connect to it via S3 and put some files there.

**Comment by dandanthedev** [comment]
> Also it would be useful if the readme documented all the env variables to set. Right now I am just trying to get it to run, then going to attempt to connect to it via S3 and put some files there.

The environment variables are defined in .env.example. I'll add a reference to that it in the readme

**Comment by dandanthedev** [comment]
I've pushed a new version. It should be working now.

**Comment by dandanthedev** [comment]
I've pushed a new version. It should be working now.

**Comment by dandanthedev** [comment]
Nevermind, the build failed

**Comment by dandanthedev** [comment]
Looks like a build succeeded now. Could you check if the issue was fixed @starsoccer?

**Comment by dandanthedev** [comment]
it'd be so much easier if i just installed docker myself haha, but i dont want it taking up all that storage

**Comment by starsoccer** [comment]
So its works better now, but struggling to actually authenticate to it with S3 Browser.

I also cant really use the web UI as it defaults to trying to ping using localhost which in my case isnt correct since I am running it in a container on another machine

**Comment by dandanthedev** [comment]
Not all S3 commands are supported yet, so that's probably why it isn't working fully. I'll look into S3 browser, it seems like a good way to implement some more commands.

As for the webui, it should ask you for the api domain when it fails to connect. It might take a few seconds

**Comment by dandanthedev** [comment]
@starsoccer i've just released a new version that implements atleast the basic commands properly. Could you test?

**Comment by starsoccer** [comment]
Yeah the webUI I was able to get working now.

S3 Browser is still giving me trouble complaining about credentials missing:
![image](https://github.com/user-attachments/assets/ef5dfd57-b890-4bc0-b570-adadf953999a)

Just to confirm I should connect using the S3 port, 7997 in this case right? and then access key & secret key for testing purposes I have set to the same thing. 

Is there some other s3 software you have tested with that I can give a try?

**Comment by dandanthedev** [comment]
> Yeah the webUI I was able to get working now.
> 
> S3 Browser is still giving me trouble complaining about credentials missing: ![image](https://private-user-images.githubusercontent.com/1938666/356815715-ef5dfd57-b890-4bc0-b570-adadf953999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMjQ5MDUsIm5iZiI6MTcyMzMyNDYwNSwicGF0aCI6Ii8xOTM4NjY2LzM1NjgxNTcxNS1lZjVkZmQ1Ny1iODkwLTRiYzAtYjU3MC1hZGFkZjk1Mzk5OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMjExNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljOGVjZDBkZTE1NWJhNzMyZGMzNmVlMDI3MWNiZjk0NmY2YTI2MzQ4MWQ1MmVmNTc4ZGY4MDJkMDA0MGE0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x-zcwcopT10aA41Q-KAmrMNoec0PyRST8C0ic4VhBag)
> 
> Just to confirm I should connect using the S3 port, 7997 in this case right? and then access key & secret key for testing purposes I have set to the same thing.
> 
> Is there some other s3 software you have tested with that I can give a try?

Hmm, that's weird. I tried with the exact program you were using and it just worked. Are you sure your api key is correct and/or have you changed anything from the default config?

**Comment by starsoccer** [comment]
> > Yeah the webUI I was able to get working now.
> > S3 Browser is still giving me trouble complaining about credentials missing: ![image](https://private-user-images.githubusercontent.com/1938666/356815715-ef5dfd57-b890-4bc0-b570-adadf953999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMjQ5MDUsIm5iZiI6MTcyMzMyNDYwNSwicGF0aCI6Ii8xOTM4NjY2LzM1NjgxNTcxNS1lZjVkZmQ1Ny1iODkwLTRiYzAtYjU3MC1hZGFkZjk1Mzk5OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMjExNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljOGVjZDBkZTE1NWJhNzMyZGMzNmVlMDI3MWNiZjk0NmY2YTI2MzQ4MWQ1MmVmNTc4ZGY4MDJkMDA0MGE0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x-zcwcopT10aA41Q-KAmrMNoec0PyRST8C0ic4VhBag)
> > Just to confirm I should connect using the S3 port, 7997 in this case right? and then access key & secret key for testing purposes I have set to the same thing.
> > Is there some other s3 software you have tested with that I can give a try?
> 
> Hmm, that's weird. I tried with the exact program you were using and it just worked. Are you sure your api key is correct and/or have you changed anything from the default config?

Yup using 100% the default config. Have not changed a thing just copy/pasted it. Can you take a picture of your S3 browser account window just to confirm I am doing everything exactly the same

**Comment by dandanthedev** [comment]
> > > Yeah the webUI I was able to get working now.
> > > S3 Browser is still giving me trouble complaining about credentials missing: ![image](https://private-user-images.githubusercontent.com/1938666/356815715-ef5dfd57-b890-4bc0-b570-adadf953999a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMjQ5MDUsIm5iZiI6MTcyMzMyNDYwNSwicGF0aCI6Ii8xOTM4NjY2LzM1NjgxNTcxNS1lZjVkZmQ1Ny1iODkwLTRiYzAtYjU3MC1hZGFkZjk1Mzk5OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMjExNjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTljOGVjZDBkZTE1NWJhNzMyZGMzNmVlMDI3MWNiZjk0NmY2YTI2MzQ4MWQ1MmVmNTc4ZGY4MDJkMDA0MGE0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x-zcwcopT10aA41Q-KAmrMNoec0PyRST8C0ic4VhBag)
> > > Just to confirm I should connect using the S3 port, 7997 in this case right? and then access key & secret key for testing purposes I have set to the same thing.
> > > Is there some other s3 software you have tested with that I can give a try?
> > 
> > 
> > Hmm, that's weird. I tried with the exact program you were using and it just worked. Are you sure your api key is correct and/or have you changed anything from the default config?
> 
> Yup using 100% the default config. Have not changed a thing just copy/pasted it. Can you take a picture of your S3 browser account window just to confirm I am doing everything exactly the same

![Arc_BtXbygn9Nv](https://github.com/user-attachments/assets/3e95158a-3eec-48d0-97ca-4ba36167bc73)

**Comment by starsoccer** [comment]
Hmm thats strange, mine is exactly the same just instead of localhost I have an ip address. Could some config option being blocking it?

Also last question, but if you go to localhosst:7997 what do you see exactly? I tried and get:
```
<Error>
<Code>AuthorizationMissing</Code>
</Error>
```
