### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by OscarNOW** [dandanthedev/littletinystorage#42]
The readme is currently the default create svelte app readme. I would recommend updating this to include some more information.

**Comment by OscarNOW** [comment]
@dandanthedev

**Comment by dandanthedev** [comment]
Thank you for your suggestion, i am not currently looking for help on this repo.

**Comment by OscarNOW** [comment]
Thank you for reopening!

**Comment by dandanthedev** [comment]
F + L + Ratio
